### ISSUE TITLE
Fix RSA encryption ArrayIndexOutOfBound bug

### ISSUE THREAD

**Issue by matchy233** [7942jun/mpc-project#3]
Generation of the private key requires one of the workers to start a trial decryption by using the public key to encrypt a test message and then decyrpt by trial and error (candidates are limited so it's okay).

However, `RSA.encrypt()` is not working properly. Thus, our application cannot function. Please fix this asap!

**Comment by CuriousLocky** [comment]
This is fixed by a recent encryption method update
